// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutUsDocumentDataSlicesSlice =
  | HeaderImageSlice
  | SummaryAboutUsSlice
  | InfoContentSlice
  | HeaderTextSlice
  | ContentWithImageSlice;

/**
 * Content for About Us documents
 */
interface AboutUsDocumentData {
  /**
   * Slice Zone field in *About Us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutUsDocumentDataSlicesSlice>
  /**
   * Meta Description field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_us.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Title field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_us.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * About Us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutUsDocumentData>,
    "about_us",
    Lang
  >;

/**
 * Content for CardEvent documents
 */
interface CardEventDocumentData {
  /**
   * title field in *CardEvent*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: card_event.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *CardEvent*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * initial_date field in *CardEvent*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: card_event.initial_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  initial_date: prismic.TimestampField;

  /**
   * final_date field in *CardEvent*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: card_event.final_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  final_date: prismic.TimestampField;

  /**
   * location field in *CardEvent*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_event.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.RichTextField;
}

/**
 * CardEvent document from Prismic
 *
 * - **API ID**: `card_event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardEventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CardEventDocumentData>,
    "card_event",
    Lang
  >;

/**
 * Content for CellCard documents
 */
interface CellCardDocumentData {
  /**
   * type field in *CellCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cell_card.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  type: prismic.RichTextField;

  /**
   * name field in *CellCard*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: cell_card.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * description field in *CellCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cell_card.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * week_day field in *CellCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cell_card.week_day
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  week_day: prismic.RichTextField;

  /**
   * initial_time field in *CellCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cell_card.initial_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  initial_time: prismic.RichTextField;

  /**
   * location field in *CellCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cell_card.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.RichTextField;

  /**
   * leader field in *CellCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cell_card.leader
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  leader: prismic.RichTextField;
}

/**
 * CellCard document from Prismic
 *
 * - **API ID**: `cell_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CellCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CellCardDocumentData>,
    "cell_card",
    Lang
  >;

type EventsDocumentDataSlicesSlice = HeaderImageSlice | HeaderTextSlice;

/**
 * Content for Events documents
 */
interface EventsDocumentData {
  /**
   * Slice Zone field in *Events*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: events.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventsDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: events.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Title field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: events.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Events document from Prismic
 *
 * - **API ID**: `events`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EventsDocumentData>,
    "events",
    Lang
  >;

/**
 * Item in *Footer → site_info*
 */
export interface FooterDocumentDataSiteInfoItem {
  /**
   * schedules field in *Footer → site_info*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.site_info[].schedules
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  schedules: prismic.RichTextField;

  /**
   * address field in *Footer → site_info*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.site_info[].address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * mail field in *Footer → site_info*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.site_info[].mail
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  mail: prismic.RichTextField;

  /**
   * logo_anglicana field in *Footer → site_info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.site_info[].logo_anglicana
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_anglicana: prismic.ImageField<never>;
}

/**
 * Item in *Footer → social_media*
 */
export interface FooterDocumentDataSocialMediaItem {
  /**
   * instagram field in *Footer → social_media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].instagram
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;

  /**
   * facebook field in *Footer → social_media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].facebook
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField;

  /**
   * youtube field in *Footer → social_media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].youtube
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  youtube: prismic.LinkField;
}

/**
 * Item in *Footer → recommendation*
 */
export interface FooterDocumentDataRecommendationItem {
  /**
   * external_link field in *Footer → recommendation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.recommendation[].external_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  external_link: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * site_info field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.site_info[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  site_info: prismic.GroupField<Simplify<FooterDocumentDataSiteInfoItem>>;

  /**
   * social_media field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<Simplify<FooterDocumentDataSocialMediaItem>>;

  /**
   * recommendation field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.recommendation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  recommendation: prismic.GroupField<
    Simplify<FooterDocumentDataRecommendationItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | HeaderImageSlice
  | HeaderTextSlice
  | WeDoingBlockSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for LiveSermon documents
 */
interface LiveSermonDocumentData {
  /**
   * live_youtube field in *LiveSermon*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: live_sermon.live_youtube
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  live_youtube: prismic.EmbedField;

  /**
   * heading field in *LiveSermon*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: live_sermon.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * quote field in *LiveSermon*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: live_sermon.quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;
}

/**
 * LiveSermon document from Prismic
 *
 * - **API ID**: `live_sermon`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LiveSermonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LiveSermonDocumentData>,
    "live_sermon",
    Lang
  >;

/**
 * Item in *Navbar → menu_itens*
 */
export interface NavbarDocumentDataMenuItensItem {
  /**
   * label field in *Navbar → menu_itens*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_itens[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * link field in *Navbar → menu_itens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_itens[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * menu_itens field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_itens[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_itens: prismic.GroupField<Simplify<NavbarDocumentDataMenuItensItem>>;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

/**
 * Content for PeopleCard documents
 */
interface PeopleCardDocumentData {
  /**
   * image field in *PeopleCard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: people_card.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * role field in *PeopleCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people_card.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  role: prismic.RichTextField;

  /**
   * heading field in *PeopleCard*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: people_card.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * department field in *PeopleCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people_card.department
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  department: prismic.RichTextField;

  /**
   * church field in *PeopleCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people_card.church
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  church: prismic.RichTextField;

  /**
   * facebook field in *PeopleCard*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: people_card.facebook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField;

  /**
   * instagram field in *PeopleCard*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: people_card.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;
}

/**
 * PeopleCard document from Prismic
 *
 * - **API ID**: `people_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PeopleCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PeopleCardDocumentData>,
    "people_card",
    Lang
  >;

/**
 * Content for RecurrentEventCard documents
 */
interface RecurrentEventCardDocumentData {
  /**
   * type field in *RecurrentEventCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recurrent_event_card.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  type: prismic.RichTextField;

  /**
   * name field in *RecurrentEventCard*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: recurrent_event_card.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * description field in *RecurrentEventCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recurrent_event_card.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * recurrent_day field in *RecurrentEventCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recurrent_event_card.recurrent_day
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  recurrent_day: prismic.RichTextField;

  /**
   * initial_time field in *RecurrentEventCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recurrent_event_card.initial_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  initial_time: prismic.RichTextField;

  /**
   * location field in *RecurrentEventCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recurrent_event_card.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.RichTextField;
}

/**
 * RecurrentEventCard document from Prismic
 *
 * - **API ID**: `recurrent_event_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RecurrentEventCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RecurrentEventCardDocumentData>,
    "recurrent_event_card",
    Lang
  >;

/**
 * Content for RegisterCardEvent documents
 */
interface RegisterCardEventDocumentData {
  /**
   * image field in *RegisterCardEvent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: register_card_event.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *RegisterCardEvent*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: register_card_event.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *RegisterCardEvent*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: register_card_event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * initial_date field in *RegisterCardEvent*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: register_card_event.initial_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  initial_date: prismic.TimestampField;

  /**
   * final_date field in *RegisterCardEvent*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: register_card_event.final_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  final_date: prismic.TimestampField;

  /**
   * location field in *RegisterCardEvent*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: register_card_event.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.RichTextField;

  /**
   * inscription_link field in *RegisterCardEvent*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: register_card_event.inscription_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  inscription_link: prismic.LinkField;
}

/**
 * RegisterCardEvent document from Prismic
 *
 * - **API ID**: `register_card_event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RegisterCardEventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RegisterCardEventDocumentData>,
    "register_card_event",
    Lang
  >;

/**
 * Content for SermonCard documents
 */
interface SermonCardDocumentData {
  /**
   * series field in *SermonCard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sermon_card.series
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  series: prismic.KeyTextField;

  /**
   * title field in *SermonCard*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: sermon_card.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *SermonCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sermon_card.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * initial_date field in *SermonCard*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: sermon_card.initial_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  initial_date: prismic.TimestampField;

  /**
   * final_date field in *SermonCard*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: sermon_card.final_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  final_date: prismic.TimestampField;

  /**
   * location field in *SermonCard*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sermon_card.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.RichTextField;
}

/**
 * SermonCard document from Prismic
 *
 * - **API ID**: `sermon_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SermonCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SermonCardDocumentData>,
    "sermon_card",
    Lang
  >;

type SermonsDocumentDataSlicesSlice = HeaderTextSlice | HeaderImageSlice;

/**
 * Content for Sermons documents
 */
interface SermonsDocumentData {
  /**
   * Slice Zone field in *Sermons*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sermons.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SermonsDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Sermons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: sermons.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Title field in *Sermons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: sermons.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Sermons document from Prismic
 *
 * - **API ID**: `sermons`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SermonsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SermonsDocumentData>,
    "sermons",
    Lang
  >;

export type AllDocumentTypes =
  | AboutUsDocument
  | CardEventDocument
  | CellCardDocument
  | EventsDocument
  | FooterDocument
  | HomeDocument
  | LiveSermonDocument
  | NavbarDocument
  | PeopleCardDocument
  | RecurrentEventCardDocument
  | RegisterCardEventDocument
  | SermonCardDocument
  | SermonsDocument;

/**
 * Primary content in *ContentWithImage → Items*
 */
export interface ContentWithImageSliceDefaultItem {
  /**
   * image field in *ContentWithImage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * heading field in *ContentWithImage → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * content field in *ContentWithImage → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for ContentWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ContentWithImageSliceDefaultItem>
>;

/**
 * Primary content in *ContentWithImage → Items*
 */
export interface ContentWithImageSliceLeftImageItem {
  /**
   * image field in *ContentWithImage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * heading field in *ContentWithImage → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * content field in *ContentWithImage → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_with_image.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * LeftImage variation for ContentWithImage Slice
 *
 * - **API ID**: `leftImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWithImageSliceLeftImage = prismic.SharedSliceVariation<
  "leftImage",
  Record<string, never>,
  Simplify<ContentWithImageSliceLeftImageItem>
>;

/**
 * Slice variation for *ContentWithImage*
 */
type ContentWithImageSliceVariation =
  | ContentWithImageSliceDefault
  | ContentWithImageSliceLeftImage;

/**
 * ContentWithImage Shared Slice
 *
 * - **API ID**: `content_with_image`
 * - **Description**: ContentWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentWithImageSlice = prismic.SharedSlice<
  "content_with_image",
  ContentWithImageSliceVariation
>;

/**
 * Primary content in *HeaderImage → Primary*
 */
export interface HeaderImageSliceDefaultPrimary {
  /**
   * background_image field in *HeaderImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_image.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * label field in *HeaderImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_image.primary.label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * title field in *HeaderImage → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Default variation for HeaderImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeaderImage*
 */
type HeaderImageSliceVariation = HeaderImageSliceDefault;

/**
 * HeaderImage Shared Slice
 *
 * - **API ID**: `header_image`
 * - **Description**: HeaderImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderImageSlice = prismic.SharedSlice<
  "header_image",
  HeaderImageSliceVariation
>;

/**
 * Primary content in *HeaderText → Primary*
 */
export interface HeaderTextSliceDefaultPrimary {
  /**
   * sub_heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.TitleField;

  /**
   * heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Default variation for HeaderText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeaderText → Primary*
 */
export interface HeaderTextSliceWithoutSubHeadingPrimary {
  /**
   * heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * WithoutSubHeading variation for HeaderText Slice
 *
 * - **API ID**: `withoutSubHeading`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSliceWithoutSubHeading = prismic.SharedSliceVariation<
  "withoutSubHeading",
  Simplify<HeaderTextSliceWithoutSubHeadingPrimary>,
  never
>;

/**
 * Primary content in *HeaderText → Primary*
 */
export interface HeaderTextSliceWithDescriptionPrimary {
  /**
   * sub_heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.TitleField;

  /**
   * heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * description field in *HeaderText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * WithDescription variation for HeaderText Slice
 *
 * - **API ID**: `withDescription`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSliceWithDescription = prismic.SharedSliceVariation<
  "withDescription",
  Simplify<HeaderTextSliceWithDescriptionPrimary>,
  never
>;

/**
 * Primary content in *HeaderText → Primary*
 */
export interface HeaderTextSliceWithCardEventPrimary {
  /**
   * heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * WithCardEvent variation for HeaderText Slice
 *
 * - **API ID**: `withCardEvent`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSliceWithCardEvent = prismic.SharedSliceVariation<
  "withCardEvent",
  Simplify<HeaderTextSliceWithCardEventPrimary>,
  never
>;

/**
 * Primary content in *HeaderText → Primary*
 */
export interface HeaderTextSliceWithSermonCardPrimary {
  /**
   * heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * WithSermonCard variation for HeaderText Slice
 *
 * - **API ID**: `withSermonCard`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSliceWithSermonCard = prismic.SharedSliceVariation<
  "withSermonCard",
  Simplify<HeaderTextSliceWithSermonCardPrimary>,
  never
>;

/**
 * Primary content in *HeaderText → Primary*
 */
export interface HeaderTextSliceWithRegisterCardEventPrimary {
  /**
   * sub_heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.TitleField;

  /**
   * heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * WithRegisterCardEvent variation for HeaderText Slice
 *
 * - **API ID**: `withRegisterCardEvent`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSliceWithRegisterCardEvent = prismic.SharedSliceVariation<
  "withRegisterCardEvent",
  Simplify<HeaderTextSliceWithRegisterCardEventPrimary>,
  never
>;

/**
 * Primary content in *HeaderText → Primary*
 */
export interface HeaderTextSliceWithPeopleCardPrimary {
  /**
   * sub_heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.TitleField;

  /**
   * heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * WithPeopleCard variation for HeaderText Slice
 *
 * - **API ID**: `withPeopleCard`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSliceWithPeopleCard = prismic.SharedSliceVariation<
  "withPeopleCard",
  Simplify<HeaderTextSliceWithPeopleCardPrimary>,
  never
>;

/**
 * Primary content in *HeaderText → Primary*
 */
export interface HeaderTextSliceWithCellCardPrimary {
  /**
   * sub_heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.TitleField;

  /**
   * heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * WithCellCard variation for HeaderText Slice
 *
 * - **API ID**: `withCellCard`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSliceWithCellCard = prismic.SharedSliceVariation<
  "withCellCard",
  Simplify<HeaderTextSliceWithCellCardPrimary>,
  never
>;

/**
 * Primary content in *HeaderText → Primary*
 */
export interface HeaderTextSliceWithRecurrentEventPrimary {
  /**
   * heading field in *HeaderText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * is_color field in *HeaderText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: header_text.primary.is_color
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_color: prismic.BooleanField;
}

/**
 * WithRecurrentEvent variation for HeaderText Slice
 *
 * - **API ID**: `withRecurrentEvent`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSliceWithRecurrentEvent = prismic.SharedSliceVariation<
  "withRecurrentEvent",
  Simplify<HeaderTextSliceWithRecurrentEventPrimary>,
  never
>;

/**
 * Slice variation for *HeaderText*
 */
type HeaderTextSliceVariation =
  | HeaderTextSliceDefault
  | HeaderTextSliceWithoutSubHeading
  | HeaderTextSliceWithDescription
  | HeaderTextSliceWithCardEvent
  | HeaderTextSliceWithSermonCard
  | HeaderTextSliceWithRegisterCardEvent
  | HeaderTextSliceWithPeopleCard
  | HeaderTextSliceWithCellCard
  | HeaderTextSliceWithRecurrentEvent;

/**
 * HeaderText Shared Slice
 *
 * - **API ID**: `header_text`
 * - **Description**: HeaderText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSlice = prismic.SharedSlice<
  "header_text",
  HeaderTextSliceVariation
>;

/**
 * Primary content in *InfoContent → Items*
 */
export interface InfoContentSliceDefaultItem {
  /**
   * label field in *InfoContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_content.items[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * heading field in *InfoContent → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: info_content.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * description field in *InfoContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_content.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for InfoContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<InfoContentSliceDefaultItem>
>;

/**
 * Slice variation for *InfoContent*
 */
type InfoContentSliceVariation = InfoContentSliceDefault;

/**
 * InfoContent Shared Slice
 *
 * - **API ID**: `info_content`
 * - **Description**: InfoContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoContentSlice = prismic.SharedSlice<
  "info_content",
  InfoContentSliceVariation
>;

/**
 * Primary content in *SummaryAboutUs → Items*
 */
export interface SummaryAboutUsSliceDefaultItem {
  /**
   * image field in *SummaryAboutUs → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: summary_about_us.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SummaryAboutUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SummaryAboutUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SummaryAboutUsSliceDefaultItem>
>;

/**
 * Slice variation for *SummaryAboutUs*
 */
type SummaryAboutUsSliceVariation = SummaryAboutUsSliceDefault;

/**
 * SummaryAboutUs Shared Slice
 *
 * - **API ID**: `summary_about_us`
 * - **Description**: SummaryAboutUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SummaryAboutUsSlice = prismic.SharedSlice<
  "summary_about_us",
  SummaryAboutUsSliceVariation
>;

/**
 * Primary content in *WeDoingBlock → Primary*
 */
export interface WeDoingBlockSliceDefaultPrimary {
  /**
   * sub_heading field in *WeDoingBlock → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: we_doing_block.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.TitleField;

  /**
   * heading field in *WeDoingBlock → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: we_doing_block.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Primary content in *WeDoingBlock → Items*
 */
export interface WeDoingBlockSliceDefaultItem {
  /**
   * type field in *WeDoingBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: hand-heart/broadcast/hands-cross
   * - **API ID Path**: we_doing_block.items[].type
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  type: prismic.RichTextField;

  /**
   * heading field in *WeDoingBlock → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: we_doing_block.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * paragraph field in *WeDoingBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Máximo de 123 caracteres
   * - **API ID Path**: we_doing_block.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for WeDoingBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WeDoingBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WeDoingBlockSliceDefaultPrimary>,
  Simplify<WeDoingBlockSliceDefaultItem>
>;

/**
 * Slice variation for *WeDoingBlock*
 */
type WeDoingBlockSliceVariation = WeDoingBlockSliceDefault;

/**
 * WeDoingBlock Shared Slice
 *
 * - **API ID**: `we_doing_block`
 * - **Description**: WeDoingBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WeDoingBlockSlice = prismic.SharedSlice<
  "we_doing_block",
  WeDoingBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutUsDocument,
      AboutUsDocumentData,
      AboutUsDocumentDataSlicesSlice,
      CardEventDocument,
      CardEventDocumentData,
      CellCardDocument,
      CellCardDocumentData,
      EventsDocument,
      EventsDocumentData,
      EventsDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LiveSermonDocument,
      LiveSermonDocumentData,
      NavbarDocument,
      NavbarDocumentData,
      PeopleCardDocument,
      PeopleCardDocumentData,
      RecurrentEventCardDocument,
      RecurrentEventCardDocumentData,
      RegisterCardEventDocument,
      RegisterCardEventDocumentData,
      SermonCardDocument,
      SermonCardDocumentData,
      SermonsDocument,
      SermonsDocumentData,
      SermonsDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentWithImageSlice,
      ContentWithImageSliceVariation,
      ContentWithImageSliceDefault,
      ContentWithImageSliceLeftImage,
      HeaderImageSlice,
      HeaderImageSliceVariation,
      HeaderImageSliceDefault,
      HeaderTextSlice,
      HeaderTextSliceVariation,
      HeaderTextSliceDefault,
      HeaderTextSliceWithoutSubHeading,
      HeaderTextSliceWithDescription,
      HeaderTextSliceWithCardEvent,
      HeaderTextSliceWithSermonCard,
      HeaderTextSliceWithRegisterCardEvent,
      HeaderTextSliceWithPeopleCard,
      HeaderTextSliceWithCellCard,
      HeaderTextSliceWithRecurrentEvent,
      InfoContentSlice,
      InfoContentSliceVariation,
      InfoContentSliceDefault,
      SummaryAboutUsSlice,
      SummaryAboutUsSliceVariation,
      SummaryAboutUsSliceDefault,
      WeDoingBlockSlice,
      WeDoingBlockSliceVariation,
      WeDoingBlockSliceDefault,
    };
  }
}
