// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type AboutDocumentDataSlicesSlice =
  | PastoralTeamSlice
  | TextBlockSlice
  | HeaderImageSlice

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, 'about', Lang>

/**
 * Content for Discipleship documents
 */
interface DiscipleshipDocumentData {
  /**
   * title field in *Discipleship*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome do grupo de discipulado
   * - **API ID Path**: discipleship.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * week_day field in *Discipleship*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Dia da semana que o GD acontece
   * - **API ID Path**: discipleship.week_day
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  week_day: prismic.KeyTextField

  /**
   * schedule field in *Discipleship*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Horário que inicia o GD (exemplo 19h)
   * - **API ID Path**: discipleship.schedule
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  schedule: prismic.KeyTextField

  /**
   * biweekly field in *Discipleship*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: discipleship.biweekly
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  biweekly: prismic.BooleanField

  /**
   * address field in *Discipleship*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Endereço do local do GD (apenas bairro e cidade)
   * - **API ID Path**: discipleship.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField

  /**
   * leader field in *Discipleship*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome do líder do GD
   * - **API ID Path**: discipleship.leader
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  leader: prismic.KeyTextField
}

/**
 * Discipleship document from Prismic
 *
 * - **API ID**: `discipleship`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DiscipleshipDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DiscipleshipDocumentData>,
    'discipleship',
    Lang
  >

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * name field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome do evento
   * - **API ID Path**: event.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do evento
   * - **API ID Path**: event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * week_day field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Dia da semana
   * - **API ID Path**: event.week_day
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  week_day: prismic.KeyTextField

  /**
   * schedule field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Horário que inicia o evento (exemplo 19h)
   * - **API ID Path**: event.schedule
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  schedule: prismic.KeyTextField

  /**
   * biweekly field in *Event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event.biweekly
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  biweekly: prismic.BooleanField
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, 'event', Lang>

type EventsDocumentDataSlicesSlice =
  | EventsSectionSlice
  | HeaderTextSlice
  | HeaderImageSlice

/**
 * Content for Events documents
 */
interface EventsDocumentData {
  /**
   * Slice Zone field in *Events*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: events.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventsDocumentDataSlicesSlice> /**
   * Meta Description field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: events.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Title field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: events.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Events document from Prismic
 *
 * - **API ID**: `events`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EventsDocumentData>,
    'events',
    Lang
  >

/**
 * Item in *Footer → site_info*
 */
export interface FooterDocumentDataSiteInfoItem {
  /**
   * schedules field in *Footer → site_info*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.site_info[].schedules
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  schedules: prismic.RichTextField

  /**
   * address field in *Footer → site_info*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.site_info[].address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField

  /**
   * link_driving field in *Footer → site_info*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.site_info[].link_driving
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_driving: prismic.LinkField

  /**
   * mail field in *Footer → site_info*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.site_info[].mail
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  mail: prismic.RichTextField

  /**
   * logo_anglicana field in *Footer → site_info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.site_info[].logo_anglicana
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_anglicana: prismic.ImageField<never>
}

/**
 * Item in *Footer → social_media*
 */
export interface FooterDocumentDataSocialMediaItem {
  /**
   * instagram field in *Footer → social_media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].instagram
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField

  /**
   * facebook field in *Footer → social_media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].facebook
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField

  /**
   * youtube field in *Footer → social_media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].youtube
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  youtube: prismic.LinkField
}

/**
 * Item in *Footer → recommendation*
 */
export interface FooterDocumentDataRecommendationItem {
  /**
   * label field in *Footer → recommendation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.recommendation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * external_link field in *Footer → recommendation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.recommendation[].external_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  external_link: prismic.LinkField
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * site_info field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.site_info[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  site_info: prismic.GroupField<Simplify<FooterDocumentDataSiteInfoItem>>

  /**
   * social_media field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<Simplify<FooterDocumentDataSocialMediaItem>>

  /**
   * recommendation field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.recommendation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  recommendation: prismic.GroupField<
    Simplify<FooterDocumentDataRecommendationItem>
  >
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    'footer',
    Lang
  >

type HomeDocumentDataSlicesSlice =
  | SermonsSectionsSlice
  | DiscipleshipGroupsSlice
  | EventsSectionSlice
  | HeaderTextSlice
  | HeaderImageSlice

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>

/**
 * Item in *Navbar → menu_itens*
 */
export interface NavbarDocumentDataMenuItensItem {
  /**
   * label field in *Navbar → menu_itens*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_itens[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField

  /**
   * link field in *Navbar → menu_itens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_itens[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * menu_itens field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_itens[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_itens: prismic.GroupField<Simplify<NavbarDocumentDataMenuItensItem>>

  /**
   * whatsapp_message field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.whatsapp_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  whatsapp_message: prismic.KeyTextField

  /**
   * whatsapp_number field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 81999999999
   * - **API ID Path**: navbar.whatsapp_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  whatsapp_number: prismic.KeyTextField
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    'navbar',
    Lang
  >

/**
 * Item in *People → social_media*
 */
export interface PeopleDocumentDataSocialMediaItem {
  /**
   * instagram_profile field in *People → social_media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link para o perfil do instagram
   * - **API ID Path**: people.social_media[].instagram_profile
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram_profile: prismic.LinkField

  /**
   * facebook_profile field in *People → social_media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link para o perfil do facebook
   * - **API ID Path**: people.social_media[].facebook_profile
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook_profile: prismic.LinkField
}

/**
 * Content for People documents
 */
interface PeopleDocumentData {
  /**
   * name field in *People*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome do líder
   * - **API ID Path**: people.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * image field in *People*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: people.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * role field in *People*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cargo ou função
   * - **API ID Path**: people.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField

  /**
   * description field in *People*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do líder
   * - **API ID Path**: people.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * social_media field in *People*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: people.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<Simplify<PeopleDocumentDataSocialMediaItem>>
}

/**
 * People document from Prismic
 *
 * - **API ID**: `people`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PeopleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PeopleDocumentData>, 'people', Lang>

type SermonsDocumentDataSlicesSlice = SermonsSectionsSlice | HeaderImageSlice

/**
 * Content for Sermons documents
 */
interface SermonsDocumentData {
  /**
   * Slice Zone field in *Sermons*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sermons.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SermonsDocumentDataSlicesSlice> /**
   * Meta Description field in *Sermons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: sermons.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Title field in *Sermons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: sermons.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Sermons document from Prismic
 *
 * - **API ID**: `sermons`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SermonsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SermonsDocumentData>,
    'sermons',
    Lang
  >

export type AllDocumentTypes =
  | AboutDocument
  | DiscipleshipDocument
  | EventDocument
  | EventsDocument
  | FooterDocument
  | HomeDocument
  | NavbarDocument
  | PeopleDocument
  | SermonsDocument

/**
 * Primary content in *DiscipleshipGroupsSection → Default → Primary*
 */
export interface DiscipleshipGroupsSliceDefaultPrimary {
  /**
   * title field in *DiscipleshipGroupsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discipleship_groups.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * description field in *DiscipleshipGroupsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discipleship_groups.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * image field in *DiscipleshipGroupsSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: discipleship_groups.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * phones field in *DiscipleshipGroupsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discipleship_groups.default.primary.phones
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phones: prismic.RichTextField
}

/**
 * Primary content in *DiscipleshipGroupsSection → Items*
 */
export interface DiscipleshipGroupsSliceDefaultItem {
  /**
   * Discipleships field in *DiscipleshipGroupsSection → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: discipleship_groups.items[].discipleships
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  discipleships: prismic.ContentRelationshipField<'discipleship'>
}

/**
 * Default variation for DiscipleshipGroupsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscipleshipGroupsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<DiscipleshipGroupsSliceDefaultPrimary>,
  Simplify<DiscipleshipGroupsSliceDefaultItem>
>

/**
 * Slice variation for *DiscipleshipGroupsSection*
 */
type DiscipleshipGroupsSliceVariation = DiscipleshipGroupsSliceDefault

/**
 * DiscipleshipGroupsSection Shared Slice
 *
 * - **API ID**: `discipleship_groups`
 * - **Description**: DiscipleshipGroups
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscipleshipGroupsSlice = prismic.SharedSlice<
  'discipleship_groups',
  DiscipleshipGroupsSliceVariation
>

/**
 * Primary content in *EventsSection → Default → Primary*
 */
export interface EventsSectionSliceDefaultPrimary {
  /**
   * title field in *EventsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Título da seção de eventos
   * - **API ID Path**: events_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField
}

/**
 * Primary content in *EventsSection → Items*
 */
export interface EventsSectionSliceDefaultItem {
  /**
   * events field in *EventsSection → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.items[].events
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  events: prismic.ContentRelationshipField<'event'>
}

/**
 * Default variation for EventsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<EventsSectionSliceDefaultPrimary>,
  Simplify<EventsSectionSliceDefaultItem>
>

/**
 * Slice variation for *EventsSection*
 */
type EventsSectionSliceVariation = EventsSectionSliceDefault

/**
 * EventsSection Shared Slice
 *
 * - **API ID**: `events_section`
 * - **Description**: EventsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSectionSlice = prismic.SharedSlice<
  'events_section',
  EventsSectionSliceVariation
>

/**
 * Primary content in *HeaderImage → Default → Primary*
 */
export interface HeaderImageSliceDefaultPrimary {
  /**
   * background_image field in *HeaderImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_image.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>

  /**
   * label field in *HeaderImage → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Subtítulo da página
   * - **API ID Path**: header_image.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField

  /**
   * title field in *HeaderImage → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título da página
   * - **API ID Path**: header_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField
}

/**
 * Default variation for HeaderImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderImageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeaderImageSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *HeaderImage*
 */
type HeaderImageSliceVariation = HeaderImageSliceDefault

/**
 * HeaderImage Shared Slice
 *
 * - **API ID**: `header_image`
 * - **Description**: HeaderImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderImageSlice = prismic.SharedSlice<
  'header_image',
  HeaderImageSliceVariation
>

/**
 * Primary content in *HeaderTextImage → Default → Primary*
 */
export interface HeaderTextSliceDefaultPrimary {
  /**
   * title field in *HeaderTextImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * description field in *HeaderTextImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * image field in *HeaderTextImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for HeaderTextImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeaderTextSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *HeaderTextImage*
 */
type HeaderTextSliceVariation = HeaderTextSliceDefault

/**
 * HeaderTextImage Shared Slice
 *
 * - **API ID**: `header_text`
 * - **Description**: HeaderText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderTextSlice = prismic.SharedSlice<
  'header_text',
  HeaderTextSliceVariation
>

/**
 * Primary content in *PastoralTeam → Default → Primary*
 */
export interface PastoralTeamSliceDefaultPrimary {
  /**
   * heading field in *PastoralTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pastoral_team.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField
}

/**
 * Primary content in *PastoralTeam → Items*
 */
export interface PastoralTeamSliceDefaultItem {
  /**
   * team field in *PastoralTeam → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: pastoral_team.items[].team
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  team: prismic.ContentRelationshipField<'people'>
}

/**
 * Default variation for PastoralTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PastoralTeamSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<PastoralTeamSliceDefaultPrimary>,
  Simplify<PastoralTeamSliceDefaultItem>
>

/**
 * Slice variation for *PastoralTeam*
 */
type PastoralTeamSliceVariation = PastoralTeamSliceDefault

/**
 * PastoralTeam Shared Slice
 *
 * - **API ID**: `pastoral_team`
 * - **Description**: PastoralTeam
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PastoralTeamSlice = prismic.SharedSlice<
  'pastoral_team',
  PastoralTeamSliceVariation
>

/**
 * Primary content in *SermonsSection → Default → Primary*
 */
export interface SermonsSectionsSliceDefaultPrimary {
  /**
   * title field in *SermonsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sermons_sections.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField
}

/**
 * Default variation for SermonsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SermonsSectionsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SermonsSectionsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *SermonsSection*
 */
type SermonsSectionsSliceVariation = SermonsSectionsSliceDefault

/**
 * SermonsSection Shared Slice
 *
 * - **API ID**: `sermons_sections`
 * - **Description**: SermonsSections
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SermonsSectionsSlice = prismic.SharedSlice<
  'sermons_sections',
  SermonsSectionsSliceVariation
>

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * heading field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * paragraph field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  'text_block',
  TextBlockSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      DiscipleshipDocument,
      DiscipleshipDocumentData,
      EventDocument,
      EventDocumentData,
      EventsDocument,
      EventsDocumentData,
      EventsDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSiteInfoItem,
      FooterDocumentDataSocialMediaItem,
      FooterDocumentDataRecommendationItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataMenuItensItem,
      PeopleDocument,
      PeopleDocumentData,
      PeopleDocumentDataSocialMediaItem,
      SermonsDocument,
      SermonsDocumentData,
      SermonsDocumentDataSlicesSlice,
      AllDocumentTypes,
      DiscipleshipGroupsSlice,
      DiscipleshipGroupsSliceDefaultPrimary,
      DiscipleshipGroupsSliceDefaultItem,
      DiscipleshipGroupsSliceVariation,
      DiscipleshipGroupsSliceDefault,
      EventsSectionSlice,
      EventsSectionSliceDefaultPrimary,
      EventsSectionSliceDefaultItem,
      EventsSectionSliceVariation,
      EventsSectionSliceDefault,
      HeaderImageSlice,
      HeaderImageSliceDefaultPrimary,
      HeaderImageSliceVariation,
      HeaderImageSliceDefault,
      HeaderTextSlice,
      HeaderTextSliceDefaultPrimary,
      HeaderTextSliceVariation,
      HeaderTextSliceDefault,
      PastoralTeamSlice,
      PastoralTeamSliceDefaultPrimary,
      PastoralTeamSliceDefaultItem,
      PastoralTeamSliceVariation,
      PastoralTeamSliceDefault,
      SermonsSectionsSlice,
      SermonsSectionsSliceDefaultPrimary,
      SermonsSectionsSliceVariation,
      SermonsSectionsSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    }
  }
}
