export { getEvents, getEventsByUID } from './getEvents'
export { getHome } from './getHome'
export { getSettings } from './getSettings'
export { getSermons } from './getSermons'
export { getDiscipleshipByUID } from './getDiscipleship'
export { getAbout } from './getAbout'
export { getPeopleByUID } from './getPeople'
