// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  discipleship_groups: dynamic(() => import('./DiscipleshipGroupsSection')),
  events_section: dynamic(() => import('./EventsSection')),
  header_image: dynamic(() => import('./HeaderImage')),
  header_text: dynamic(() => import('./HeaderTextImage')),
  sermons_sections: dynamic(() => import('./SermonsSection')),
  subscription_section: dynamic(() => import('./SubscriptionsSection')),
}
