// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  discipleship_groups: dynamic(() => import('./DiscipleshipGroupsSection')),
  events_section: dynamic(() => import('./EventsSection')),
  header_image: dynamic(() => import('./HeaderImage')),
  header_text: dynamic(() => import('./HeaderTextImage')),
  pastoral_team: dynamic(() => import('./PastoralTeam')),
  sermons_sections: dynamic(() => import('./SermonsSection')),
  text_block: dynamic(() => import('./TextBlock')),
}
