// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  discipleship_groups: dynamic(() => import('./DiscipleshipGroups')),
  events_section: dynamic(() => import('./EventsSection')),
  header_image: dynamic(() => import('./HeaderImage')),
  header_text: dynamic(() => import('./HeaderText')),
}
